server:
  port: 7979
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#zuul:
#  routes:
#    user-route:
#      path: /user/**
#      serviceId: user-service

# URL 路由
zuul:
  routes:
    user-servic:
      path: /user/**
      url: http://127.0.0.1:8181/
# 前缀路由
#zuul:
#  prefix: /openapi
#  routes:
#    user-service:
#      path: /user-service/**

