server:
  port: 8381
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: hystrix-client
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
     exposure:
      include: hystrix.stream